// ATS-Friendly Resume Data Structure
// Optimized for: LinkedIn, Indeed, Google Cloud Talent, Workday, Greenhouse

export const resumeData = {
  personal: {
    name: 'Akshat Kumar Singh',
    title: 'Senior Frontend Engineer',
    email: 'work.iamakshat@gmail.com',
    phone: '+91-9634780846',
    location: 'Noida, India',
    portfolio: 'https://akshat-portfolio-xi.vercel.app',
    github: 'https://github.com/Akshat53',
    linkedin: 'https://linkedin.com/in/akshat53',
  },

  summary:
    'Results-driven Senior Frontend Engineer with 3+ years of production experience building high-performance, scalable SaaS applications. Expert in React.js, Next.js, TypeScript, and real-time systems. Proven track record of 30%+ performance improvements and successful delivery of mission-critical products at SparkTG serving 500+ enterprise clients. Specialized in building embeddable widgets, complex dashboards, and accessible web applications.',

  experience: [
    {
      company: 'SparkTG',
      position: 'Frontend Engineer',
      duration: 'February 2025 – Present',
      location: 'Noida, India',
      description: 'AI-Powered Cloud Communication Platform (Cloud Telephony, IVR, AI Voice Bots)',
      achievements: [
        'Built complete SparkTG website (sparktg.com) - modern marketing platform with 98+ Lighthouse score, full SEO optimization, and responsive design',
        'Redesigned Portal v2 dashboard - enterprise contact center UI serving 500+ clients, handling real-time conversation management with 50M+ calls/month',
        'Developed SparkChat - embeddable SaaS chatbot widget integrated into 100+ client websites with <500ms latency and 99.9% uptime',
        'Built Calling Widget - integrable voice calling widget used by Zomato Nugget, Eternal, and multiple enterprise clients',
        'Optimized dashboard performance by 35% through code splitting, memoization, virtualization, and Redux optimization',
        'Implemented real-time message synchronization with optimistic UI updates, handling 2.4M+ concurrent conversations',
        'Designed and maintained component library and design tokens system across Website, Dashboard, and Widgets',
        'Achieved 25-30% UX improvement in Portal v2 through accessibility optimization (WCAG AA compliance)',
        'Working with AI tools (Claude Code, Codex) for accelerated development and code generation',
        'Led frontend architecture decisions for WebRTC integration, real-time WebSocket handling, and cross-domain widget communication',
      ],
      technologies: [
        'React.js',
        'Next.js',
        'TypeScript',
        'Tailwind CSS',
        'Web Components',
        'Redux',
        'WebRTC',
        'WebSockets',
        'REST APIs',
        'GraphQL',
        'Vercel',
        'Claude Code',
        'AI-assisted Development',
      ],
    },
    {
      company: 'Ellemora (Fashion E-commerce)',
      position: 'Full Stack Engineer (Frontend Heavy)',
      duration: 'August 2023 – February 2025',
      location: 'Bareilly, India',
      description: 'E-commerce Platform Development',
      achievements: [
        'Built complete fashion e-commerce platform with React.js and Next.js - product catalog, checkout flow, user dashboard',
        'Implemented server-side rendering (SSR) and progressive web app (PWA) - 40% better SEO and page load speed',
        'Integrated Stripe payment processing with secure payment handling and error recovery',
        'Built responsive UI supporting desktop, tablet, and mobile (320px-2560px)',
        'Connected Strapi CMS backend for content management and dynamic product data',
        'Achieved 98+ Lighthouse score through image optimization, code splitting, and performance tuning',
        'Implemented offline functionality with Service Workers and IndexedDB for PWA support',
      ],
      technologies: [
        'Next.js',
        'React.js',
        'Node.js',
        'Strapi CMS',
        'PostgreSQL',
        'Stripe API',
        'Tailwind CSS',
        'Service Workers',
        'PWA',
      ],
    },
    {
      company: 'Wipro Technologies',
      position: 'Project Engineer (Frontend Heavy)',
      duration: 'June 2022 – August 2023',
      location: 'Noida, India',
      description: 'Enterprise FinTech Solutions (Frontend & Spring Boot)',
      achievements: [
        'Worked on enterprise-level FinTech dashboard for Alight Solutions - financial data visualization and reporting',
        'Built frontend components with React.js and Bootstrap for complex financial workflows',
        'Developed Java Spring Boot microservices for backend APIs and data processing',
        'Migrated legacy UIs to React.js - improved performance and maintainability',
        'Improved UX by 25-30% through accessibility optimization (WCAG AA compliance) and performance tuning',
        'Built reusable components for large dataset handling and complex financial data visualization',
        'Collaborated in Agile teams with bi-weekly releases and supported QA/DevOps during integration',
        'Implemented RESTful APIs and integrated with various backend services',
      ],
      technologies: [
        'React.js',
        'Bootstrap',
        'Java',
        'Spring Boot',
        'REST APIs',
        'PostgreSQL',
        'Jenkins',
        'Jira',
        'Agile',
      ],
    },
  ],

  education: [
    {
      degree: 'Master of Computer Application (MCA)',
      institution: 'Jain University',
      location: 'Bengaluru, India',
      year: '2023-2025',
    },
    {
      degree: 'Bachelor of Computer Application (BCA)',
      institution: 'Invertis University',
      location: 'Bareilly, India',
      year: '2019-2022',
    },
  ],

  certifications: [
    {
      name: 'Microsoft Azure Fundamentals (AZ-900)',
      issuer: 'Microsoft',
      year: '2024',
    },
    {
      name: 'Progressive Web Apps (PWA) - Google Web Fundamentals',
      issuer: 'Google',
      year: '2023',
    },
  ],

  skills: {
    'Frontend Core': ['React.js', 'Next.js', 'TypeScript', 'JavaScript (ES6+)', 'HTML5', 'CSS3', 'Tailwind CSS'],
    'State & Architecture': ['Redux', 'Context API', 'Zustand', 'Custom Hooks', 'Component Architecture', 'Micro Frontends'],
    'Real-Time & APIs': ['WebRTC', 'WebSockets', 'REST APIs', 'GraphQL', 'Axios', 'Fetch API', 'Optimistic Updates'],
    'Performance & Optimization': [
      'Code Splitting',
      'Lazy Loading',
      'Memoization',
      'Virtualization',
      'Bundle Optimization',
      'Image Optimization',
      'Caching Strategies',
    ],
    'UI/UX & Design': [
      'Responsive Design',
      'Accessibility (WCAG AA)',
      'Design Systems',
      'Component Libraries',
      'ShadCN UI',
      'Bootstrap',
      'Figma',
    ],
    'Backend & Databases': ['Node.js', 'Express.js', 'Java (Spring Boot)', 'PostgreSQL', 'MySQL', 'Strapi CMS'],
    'Tools & DevOps': ['Git', 'GitHub', 'Bitbucket', 'CI/CD', 'Jenkins', 'Docker', 'Vercel', 'Agile/Jira'],
    'Web Technologies': ['PWA', 'Service Workers', 'IndexedDB', 'LocalStorage', 'WebWorkers', 'SEO Optimization'],
  },

  projects: [
    {
      name: 'SparkTG Website',
      description: 'Complete marketing website for AI-powered cloud communication platform',
      highlights: [
        '98+ Lighthouse score',
        'Full SEO optimization',
        'Responsive design (320px-2560px)',
        'Modern animations and interactions',
        'Fast load times (<1s)',
      ],
      technologies: ['Next.js', 'React.js', 'TypeScript', 'Tailwind CSS', 'Vercel'],
      link: 'https://sparktg.com',
    },
    {
      name: 'Portal v2 Dashboard',
      description: 'Enterprise contact center dashboard serving 500+ clients, handling 50M+ calls/month',
      highlights: [
        '35% performance improvement',
        '25-30% UX improvement',
        'Real-time conversation management',
        'WCAG AA accessibility compliance',
        'Handles 2.4M+ concurrent conversations',
      ],
      technologies: ['React.js', 'Redux', 'TypeScript', 'WebSockets', 'Tailwind CSS'],
    },
    {
      name: 'SparkChat Widget',
      description: 'Embeddable SaaS chatbot widget for client integration - used by 100+ clients',
      highlights: [
        '<500ms latency',
        '99.9% uptime',
        'Cross-domain isolation (Web Components)',
        'Responsive design',
        'AI-powered conversations',
      ],
      technologies: ['React.js', 'Web Components', 'TypeScript', 'REST APIs', 'WebSockets'],
    },
    {
      name: 'Calling Widget',
      description: 'Integrable voice calling widget used by Zomato Nugget, Eternal, and enterprise clients',
      highlights: [
        'Real-time voice integration',
        'Low latency calling',
        'Multi-client support',
        'Reliable connection handling',
        'Production grade',
      ],
      technologies: ['React.js', 'WebRTC', 'TypeScript', 'REST APIs'],
    },
    {
      name: 'Ellemora Fashion E-commerce',
      description: 'Full-featured fashion e-commerce platform with SSR, PWA, and Stripe integration',
      highlights: [
        '40% SEO & page load improvement (SSR)',
        '98+ Lighthouse score',
        'PWA offline support',
        'Stripe payment integration',
        'Responsive design',
      ],
      technologies: ['Next.js', 'React.js', 'Node.js', 'Strapi', 'PostgreSQL', 'Stripe', 'Service Workers'],
    },
    {
      name: 'Pocket Notes PWA',
      description: 'Offline-first note-taking progressive web app with push notifications',
      highlights: [
        'Offline-first functionality',
        'Service Workers & Cache API',
        'IndexedDB storage',
        'Push notifications',
        'Sync on reconnect',
      ],
      technologies: ['React.js', 'Service Workers', 'IndexedDB', 'Cache API', 'PWA'],
    },
  ],

  summary_short:
    'Senior Frontend Engineer | React & Next.js Specialist | Real-time Systems Expert | 3+ Years SaaS Experience',
};

// ATS Keywords (for parsing optimization)
export const atsKeywords = {
  hard_skills: [
    'React.js',
    'Next.js',
    'TypeScript',
    'JavaScript',
    'HTML',
    'CSS',
    'Tailwind',
    'Redux',
    'WebRTC',
    'WebSockets',
    'REST API',
    'GraphQL',
    'Node.js',
    'PostgreSQL',
    'Git',
    'Agile',
  ],
  soft_skills: ['Communication', 'Problem Solving', 'Team Leadership', 'Code Review', 'Mentoring', 'Agile Methodology'],
  industries: ['SaaS', 'FinTech', 'E-commerce', 'Cloud Communication', 'Enterprise Software'],
  achievements: [
    '35% performance improvement',
    '25-30% UX improvement',
    '98+ Lighthouse score',
    '500+ clients',
    '50M+ calls/month',
    '2.4M+ concurrent conversations',
  ],
};
